services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mahabub637/webhook:${IMAGE_TAG}
    container_name: kafka-boilerplate
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.example
