spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    properties:
      security:
        protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl:
        mechanism: ${KAFKA_SASL_MECHANISM:}
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:tpd-loggers}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

tpd:
  topic-name: ${ADVICE_TOPIC:advice-topic}
  messages-per-request: 10

wiki:
  url: ${WIKIMEDIA_STREAM_URL:https://stream.wikimedia.org/v2/stream/recentchange}
  topic-name: ${WIKIMEDIA_TOPIC:wikimedia}

webhhok:
  topic: ${WEBHOOK_TOPIC:event}